# Generated by Django 2.2.4 on 2019-09-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='ima',
            new_name='img',
        ),
    ]
